name: 'Git Setup'
description: 'Checkout and git auth for private repositories'
inputs:
  token:       { description: 'Access token', required: true }
  fetch-depth: { description: 'Fetch depth', required: true }

runs:
  using: composite
  steps:
    - name: Checkout git repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Configure git for private modules
      shell: bash
      run: >
        git config --global
        url."https://x-access-token:${{ inputs.token }}@github.com/".insteadOf
        "https://github.com/"
